// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package dto

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjsonE64d6f7cDecodeGithubComMmikhail2001TechnoparkDbProjectInternalAppDeliveryPostDto(in *jlexer.Lexer, out *PostUpdateMessageResponseDTO) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "id":
			out.ID = int(in.Int())
		case "parent":
			out.Parent = int(in.Int())
		case "author":
			out.Author = string(in.String())
		case "message":
			out.Message = string(in.String())
		case "isEdited":
			out.IsEdited = bool(in.Bool())
		case "forum":
			out.Forum = string(in.String())
		case "thread":
			out.Thread = int(in.Int())
		case "created":
			out.Created = string(in.String())
		default:
			in.AddError(&jlexer.LexerError{
				Offset: in.GetPos(),
				Reason: "unknown field",
				Data:   key,
			})
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonE64d6f7cEncodeGithubComMmikhail2001TechnoparkDbProjectInternalAppDeliveryPostDto(out *jwriter.Writer, in PostUpdateMessageResponseDTO) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"id\":"
		out.RawString(prefix[1:])
		out.Int(int(in.ID))
	}
	{
		const prefix string = ",\"parent\":"
		out.RawString(prefix)
		out.Int(int(in.Parent))
	}
	{
		const prefix string = ",\"author\":"
		out.RawString(prefix)
		out.String(string(in.Author))
	}
	{
		const prefix string = ",\"message\":"
		out.RawString(prefix)
		out.String(string(in.Message))
	}
	{
		const prefix string = ",\"isEdited\":"
		out.RawString(prefix)
		out.Bool(bool(in.IsEdited))
	}
	{
		const prefix string = ",\"forum\":"
		out.RawString(prefix)
		out.String(string(in.Forum))
	}
	{
		const prefix string = ",\"thread\":"
		out.RawString(prefix)
		out.Int(int(in.Thread))
	}
	{
		const prefix string = ",\"created\":"
		out.RawString(prefix)
		out.String(string(in.Created))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v PostUpdateMessageResponseDTO) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonE64d6f7cEncodeGithubComMmikhail2001TechnoparkDbProjectInternalAppDeliveryPostDto(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v PostUpdateMessageResponseDTO) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonE64d6f7cEncodeGithubComMmikhail2001TechnoparkDbProjectInternalAppDeliveryPostDto(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *PostUpdateMessageResponseDTO) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonE64d6f7cDecodeGithubComMmikhail2001TechnoparkDbProjectInternalAppDeliveryPostDto(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *PostUpdateMessageResponseDTO) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonE64d6f7cDecodeGithubComMmikhail2001TechnoparkDbProjectInternalAppDeliveryPostDto(l, v)
}
func easyjsonE64d6f7cDecodeGithubComMmikhail2001TechnoparkDbProjectInternalAppDeliveryPostDto1(in *jlexer.Lexer, out *PostUpdateMessageRequestDTO) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "ID":
			out.ID = int(in.Int())
		case "message":
			out.Message = string(in.String())
		default:
			in.AddError(&jlexer.LexerError{
				Offset: in.GetPos(),
				Reason: "unknown field",
				Data:   key,
			})
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonE64d6f7cEncodeGithubComMmikhail2001TechnoparkDbProjectInternalAppDeliveryPostDto1(out *jwriter.Writer, in PostUpdateMessageRequestDTO) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"ID\":"
		out.RawString(prefix[1:])
		out.Int(int(in.ID))
	}
	{
		const prefix string = ",\"message\":"
		out.RawString(prefix)
		out.String(string(in.Message))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v PostUpdateMessageRequestDTO) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonE64d6f7cEncodeGithubComMmikhail2001TechnoparkDbProjectInternalAppDeliveryPostDto1(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v PostUpdateMessageRequestDTO) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonE64d6f7cEncodeGithubComMmikhail2001TechnoparkDbProjectInternalAppDeliveryPostDto1(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *PostUpdateMessageRequestDTO) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonE64d6f7cDecodeGithubComMmikhail2001TechnoparkDbProjectInternalAppDeliveryPostDto1(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *PostUpdateMessageRequestDTO) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonE64d6f7cDecodeGithubComMmikhail2001TechnoparkDbProjectInternalAppDeliveryPostDto1(l, v)
}
