// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package dto

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjson3fe41b0fDecodeGithubComMmikhail2001TechnoparkDbProjectInternalAppDeliveryForumDto(in *jlexer.Lexer, out *ThreadsDTO) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		in.Skip()
		*out = nil
	} else {
		in.Delim('[')
		if *out == nil {
			if !in.IsDelim(']') {
				*out = make(ThreadsDTO, 0, 8)
			} else {
				*out = ThreadsDTO{}
			}
		} else {
			*out = (*out)[:0]
		}
		for !in.IsDelim(']') {
			var v1 *ThreadDTO
			if in.IsNull() {
				in.Skip()
				v1 = nil
			} else {
				if v1 == nil {
					v1 = new(ThreadDTO)
				}
				(*v1).UnmarshalEasyJSON(in)
			}
			*out = append(*out, v1)
			in.WantComma()
		}
		in.Delim(']')
	}
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson3fe41b0fEncodeGithubComMmikhail2001TechnoparkDbProjectInternalAppDeliveryForumDto(out *jwriter.Writer, in ThreadsDTO) {
	if in == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
		out.RawString("null")
	} else {
		out.RawByte('[')
		for v2, v3 := range in {
			if v2 > 0 {
				out.RawByte(',')
			}
			if v3 == nil {
				out.RawString("null")
			} else {
				(*v3).MarshalEasyJSON(out)
			}
		}
		out.RawByte(']')
	}
}

// MarshalJSON supports json.Marshaler interface
func (v ThreadsDTO) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson3fe41b0fEncodeGithubComMmikhail2001TechnoparkDbProjectInternalAppDeliveryForumDto(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v ThreadsDTO) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson3fe41b0fEncodeGithubComMmikhail2001TechnoparkDbProjectInternalAppDeliveryForumDto(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *ThreadsDTO) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson3fe41b0fDecodeGithubComMmikhail2001TechnoparkDbProjectInternalAppDeliveryForumDto(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *ThreadsDTO) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson3fe41b0fDecodeGithubComMmikhail2001TechnoparkDbProjectInternalAppDeliveryForumDto(l, v)
}
func easyjson3fe41b0fDecodeGithubComMmikhail2001TechnoparkDbProjectInternalAppDeliveryForumDto1(in *jlexer.Lexer, out *ThreadDTO) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "id":
			out.ID = int(in.Int())
		case "title":
			out.Title = string(in.String())
		case "author":
			out.Author = string(in.String())
		case "forum":
			out.Forum = string(in.String())
		case "slug":
			out.Slug = string(in.String())
		case "message":
			out.Message = string(in.String())
		case "created":
			out.Created = string(in.String())
		case "votes":
			out.SumVotes = int(in.Int())
		default:
			in.AddError(&jlexer.LexerError{
				Offset: in.GetPos(),
				Reason: "unknown field",
				Data:   key,
			})
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson3fe41b0fEncodeGithubComMmikhail2001TechnoparkDbProjectInternalAppDeliveryForumDto1(out *jwriter.Writer, in ThreadDTO) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"id\":"
		out.RawString(prefix[1:])
		out.Int(int(in.ID))
	}
	{
		const prefix string = ",\"title\":"
		out.RawString(prefix)
		out.String(string(in.Title))
	}
	{
		const prefix string = ",\"author\":"
		out.RawString(prefix)
		out.String(string(in.Author))
	}
	{
		const prefix string = ",\"forum\":"
		out.RawString(prefix)
		out.String(string(in.Forum))
	}
	if in.Slug != "" {
		const prefix string = ",\"slug\":"
		out.RawString(prefix)
		out.String(string(in.Slug))
	}
	{
		const prefix string = ",\"message\":"
		out.RawString(prefix)
		out.String(string(in.Message))
	}
	{
		const prefix string = ",\"created\":"
		out.RawString(prefix)
		out.String(string(in.Created))
	}
	{
		const prefix string = ",\"votes\":"
		out.RawString(prefix)
		out.Int(int(in.SumVotes))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v ThreadDTO) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson3fe41b0fEncodeGithubComMmikhail2001TechnoparkDbProjectInternalAppDeliveryForumDto1(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v ThreadDTO) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson3fe41b0fEncodeGithubComMmikhail2001TechnoparkDbProjectInternalAppDeliveryForumDto1(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *ThreadDTO) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson3fe41b0fDecodeGithubComMmikhail2001TechnoparkDbProjectInternalAppDeliveryForumDto1(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *ThreadDTO) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson3fe41b0fDecodeGithubComMmikhail2001TechnoparkDbProjectInternalAppDeliveryForumDto1(l, v)
}
