// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package dto

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjson7b5d8f5eDecodeGithubComMmikhail2001TechnoparkDbProjectInternalAppDeliveryForumDto(in *jlexer.Lexer, out *ForumDetailsResponseDTO) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "title":
			out.Title = string(in.String())
		case "user":
			out.User = string(in.String())
		case "slug":
			out.Slug = string(in.String())
		case "posts":
			out.CountPosts = int(in.Int())
		case "threads":
			out.CountThreads = int(in.Int())
		default:
			in.AddError(&jlexer.LexerError{
				Offset: in.GetPos(),
				Reason: "unknown field",
				Data:   key,
			})
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson7b5d8f5eEncodeGithubComMmikhail2001TechnoparkDbProjectInternalAppDeliveryForumDto(out *jwriter.Writer, in ForumDetailsResponseDTO) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"title\":"
		out.RawString(prefix[1:])
		out.String(string(in.Title))
	}
	{
		const prefix string = ",\"user\":"
		out.RawString(prefix)
		out.String(string(in.User))
	}
	{
		const prefix string = ",\"slug\":"
		out.RawString(prefix)
		out.String(string(in.Slug))
	}
	{
		const prefix string = ",\"posts\":"
		out.RawString(prefix)
		out.Int(int(in.CountPosts))
	}
	{
		const prefix string = ",\"threads\":"
		out.RawString(prefix)
		out.Int(int(in.CountThreads))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v ForumDetailsResponseDTO) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson7b5d8f5eEncodeGithubComMmikhail2001TechnoparkDbProjectInternalAppDeliveryForumDto(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v ForumDetailsResponseDTO) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson7b5d8f5eEncodeGithubComMmikhail2001TechnoparkDbProjectInternalAppDeliveryForumDto(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *ForumDetailsResponseDTO) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson7b5d8f5eDecodeGithubComMmikhail2001TechnoparkDbProjectInternalAppDeliveryForumDto(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *ForumDetailsResponseDTO) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson7b5d8f5eDecodeGithubComMmikhail2001TechnoparkDbProjectInternalAppDeliveryForumDto(l, v)
}
