// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package dto

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjson73d06ab4DecodeGithubComMmikhail2001TechnoparkDbProjectInternalAppDeliveryForumDto(in *jlexer.Lexer, out *UsersDTO) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		in.Skip()
		*out = nil
	} else {
		in.Delim('[')
		if *out == nil {
			if !in.IsDelim(']') {
				*out = make(UsersDTO, 0, 8)
			} else {
				*out = UsersDTO{}
			}
		} else {
			*out = (*out)[:0]
		}
		for !in.IsDelim(']') {
			var v1 *UserDTO
			if in.IsNull() {
				in.Skip()
				v1 = nil
			} else {
				if v1 == nil {
					v1 = new(UserDTO)
				}
				(*v1).UnmarshalEasyJSON(in)
			}
			*out = append(*out, v1)
			in.WantComma()
		}
		in.Delim(']')
	}
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson73d06ab4EncodeGithubComMmikhail2001TechnoparkDbProjectInternalAppDeliveryForumDto(out *jwriter.Writer, in UsersDTO) {
	if in == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
		out.RawString("null")
	} else {
		out.RawByte('[')
		for v2, v3 := range in {
			if v2 > 0 {
				out.RawByte(',')
			}
			if v3 == nil {
				out.RawString("null")
			} else {
				(*v3).MarshalEasyJSON(out)
			}
		}
		out.RawByte(']')
	}
}

// MarshalJSON supports json.Marshaler interface
func (v UsersDTO) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson73d06ab4EncodeGithubComMmikhail2001TechnoparkDbProjectInternalAppDeliveryForumDto(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v UsersDTO) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson73d06ab4EncodeGithubComMmikhail2001TechnoparkDbProjectInternalAppDeliveryForumDto(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *UsersDTO) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson73d06ab4DecodeGithubComMmikhail2001TechnoparkDbProjectInternalAppDeliveryForumDto(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *UsersDTO) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson73d06ab4DecodeGithubComMmikhail2001TechnoparkDbProjectInternalAppDeliveryForumDto(l, v)
}
func easyjson73d06ab4DecodeGithubComMmikhail2001TechnoparkDbProjectInternalAppDeliveryForumDto1(in *jlexer.Lexer, out *UserDTO) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "nickname":
			out.Nickname = string(in.String())
		case "fullname":
			out.Fullname = string(in.String())
		case "about":
			out.About = string(in.String())
		case "email":
			out.Email = string(in.String())
		default:
			in.AddError(&jlexer.LexerError{
				Offset: in.GetPos(),
				Reason: "unknown field",
				Data:   key,
			})
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson73d06ab4EncodeGithubComMmikhail2001TechnoparkDbProjectInternalAppDeliveryForumDto1(out *jwriter.Writer, in UserDTO) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"nickname\":"
		out.RawString(prefix[1:])
		out.String(string(in.Nickname))
	}
	{
		const prefix string = ",\"fullname\":"
		out.RawString(prefix)
		out.String(string(in.Fullname))
	}
	{
		const prefix string = ",\"about\":"
		out.RawString(prefix)
		out.String(string(in.About))
	}
	{
		const prefix string = ",\"email\":"
		out.RawString(prefix)
		out.String(string(in.Email))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v UserDTO) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson73d06ab4EncodeGithubComMmikhail2001TechnoparkDbProjectInternalAppDeliveryForumDto1(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v UserDTO) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson73d06ab4EncodeGithubComMmikhail2001TechnoparkDbProjectInternalAppDeliveryForumDto1(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *UserDTO) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson73d06ab4DecodeGithubComMmikhail2001TechnoparkDbProjectInternalAppDeliveryForumDto1(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *UserDTO) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson73d06ab4DecodeGithubComMmikhail2001TechnoparkDbProjectInternalAppDeliveryForumDto1(l, v)
}
