// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package dto

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjson7949aa42DecodeGithubComMmikhail2001TechnoparkDbProjectInternalAppDeliveryThreadDto(in *jlexer.Lexer, out *ThreadUpdateResponseDTO) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "id":
			out.ID = int(in.Int())
		case "title":
			out.Title = string(in.String())
		case "author":
			out.Author = string(in.String())
		case "forum":
			out.Forum = string(in.String())
		case "slug":
			out.Slug = string(in.String())
		case "message":
			out.Message = string(in.String())
		case "created":
			out.Created = string(in.String())
		case "votes":
			out.SumVotes = int(in.Int())
		default:
			in.AddError(&jlexer.LexerError{
				Offset: in.GetPos(),
				Reason: "unknown field",
				Data:   key,
			})
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson7949aa42EncodeGithubComMmikhail2001TechnoparkDbProjectInternalAppDeliveryThreadDto(out *jwriter.Writer, in ThreadUpdateResponseDTO) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"id\":"
		out.RawString(prefix[1:])
		out.Int(int(in.ID))
	}
	{
		const prefix string = ",\"title\":"
		out.RawString(prefix)
		out.String(string(in.Title))
	}
	{
		const prefix string = ",\"author\":"
		out.RawString(prefix)
		out.String(string(in.Author))
	}
	{
		const prefix string = ",\"forum\":"
		out.RawString(prefix)
		out.String(string(in.Forum))
	}
	{
		const prefix string = ",\"slug\":"
		out.RawString(prefix)
		out.String(string(in.Slug))
	}
	{
		const prefix string = ",\"message\":"
		out.RawString(prefix)
		out.String(string(in.Message))
	}
	{
		const prefix string = ",\"created\":"
		out.RawString(prefix)
		out.String(string(in.Created))
	}
	{
		const prefix string = ",\"votes\":"
		out.RawString(prefix)
		out.Int(int(in.SumVotes))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v ThreadUpdateResponseDTO) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson7949aa42EncodeGithubComMmikhail2001TechnoparkDbProjectInternalAppDeliveryThreadDto(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v ThreadUpdateResponseDTO) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson7949aa42EncodeGithubComMmikhail2001TechnoparkDbProjectInternalAppDeliveryThreadDto(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *ThreadUpdateResponseDTO) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson7949aa42DecodeGithubComMmikhail2001TechnoparkDbProjectInternalAppDeliveryThreadDto(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *ThreadUpdateResponseDTO) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson7949aa42DecodeGithubComMmikhail2001TechnoparkDbProjectInternalAppDeliveryThreadDto(l, v)
}
func easyjson7949aa42DecodeGithubComMmikhail2001TechnoparkDbProjectInternalAppDeliveryThreadDto1(in *jlexer.Lexer, out *ThreadUpdateRequestDTO) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "SlugOrID":
			out.SlugOrID = string(in.String())
		case "title":
			out.Title = string(in.String())
		case "message":
			out.Message = string(in.String())
		default:
			in.AddError(&jlexer.LexerError{
				Offset: in.GetPos(),
				Reason: "unknown field",
				Data:   key,
			})
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson7949aa42EncodeGithubComMmikhail2001TechnoparkDbProjectInternalAppDeliveryThreadDto1(out *jwriter.Writer, in ThreadUpdateRequestDTO) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"SlugOrID\":"
		out.RawString(prefix[1:])
		out.String(string(in.SlugOrID))
	}
	{
		const prefix string = ",\"title\":"
		out.RawString(prefix)
		out.String(string(in.Title))
	}
	{
		const prefix string = ",\"message\":"
		out.RawString(prefix)
		out.String(string(in.Message))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v ThreadUpdateRequestDTO) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson7949aa42EncodeGithubComMmikhail2001TechnoparkDbProjectInternalAppDeliveryThreadDto1(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v ThreadUpdateRequestDTO) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson7949aa42EncodeGithubComMmikhail2001TechnoparkDbProjectInternalAppDeliveryThreadDto1(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *ThreadUpdateRequestDTO) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson7949aa42DecodeGithubComMmikhail2001TechnoparkDbProjectInternalAppDeliveryThreadDto1(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *ThreadUpdateRequestDTO) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson7949aa42DecodeGithubComMmikhail2001TechnoparkDbProjectInternalAppDeliveryThreadDto1(l, v)
}
