// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package dto

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjsonFbeb1674DecodeGithubComMmikhail2001TechnoparkDbProjectInternalAppDeliveryThreadDto(in *jlexer.Lexer, out *PostsDTO) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		in.Skip()
		*out = nil
	} else {
		in.Delim('[')
		if *out == nil {
			if !in.IsDelim(']') {
				*out = make(PostsDTO, 0, 8)
			} else {
				*out = PostsDTO{}
			}
		} else {
			*out = (*out)[:0]
		}
		for !in.IsDelim(']') {
			var v1 *PostDTO
			if in.IsNull() {
				in.Skip()
				v1 = nil
			} else {
				if v1 == nil {
					v1 = new(PostDTO)
				}
				(*v1).UnmarshalEasyJSON(in)
			}
			*out = append(*out, v1)
			in.WantComma()
		}
		in.Delim(']')
	}
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonFbeb1674EncodeGithubComMmikhail2001TechnoparkDbProjectInternalAppDeliveryThreadDto(out *jwriter.Writer, in PostsDTO) {
	if in == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
		out.RawString("null")
	} else {
		out.RawByte('[')
		for v2, v3 := range in {
			if v2 > 0 {
				out.RawByte(',')
			}
			if v3 == nil {
				out.RawString("null")
			} else {
				(*v3).MarshalEasyJSON(out)
			}
		}
		out.RawByte(']')
	}
}

// MarshalJSON supports json.Marshaler interface
func (v PostsDTO) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonFbeb1674EncodeGithubComMmikhail2001TechnoparkDbProjectInternalAppDeliveryThreadDto(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v PostsDTO) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonFbeb1674EncodeGithubComMmikhail2001TechnoparkDbProjectInternalAppDeliveryThreadDto(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *PostsDTO) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonFbeb1674DecodeGithubComMmikhail2001TechnoparkDbProjectInternalAppDeliveryThreadDto(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *PostsDTO) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonFbeb1674DecodeGithubComMmikhail2001TechnoparkDbProjectInternalAppDeliveryThreadDto(l, v)
}
func easyjsonFbeb1674DecodeGithubComMmikhail2001TechnoparkDbProjectInternalAppDeliveryThreadDto1(in *jlexer.Lexer, out *PostDTO) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "id":
			out.ID = int(in.Int())
		case "parent":
			out.Parent = int(in.Int())
		case "author":
			out.Author = string(in.String())
		case "message":
			out.Message = string(in.String())
		case "isEdited":
			out.IsEdited = bool(in.Bool())
		case "forum":
			out.Forum = string(in.String())
		case "thread":
			out.Thread = int(in.Int())
		case "created":
			out.Created = string(in.String())
		default:
			in.AddError(&jlexer.LexerError{
				Offset: in.GetPos(),
				Reason: "unknown field",
				Data:   key,
			})
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonFbeb1674EncodeGithubComMmikhail2001TechnoparkDbProjectInternalAppDeliveryThreadDto1(out *jwriter.Writer, in PostDTO) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"id\":"
		out.RawString(prefix[1:])
		out.Int(int(in.ID))
	}
	{
		const prefix string = ",\"parent\":"
		out.RawString(prefix)
		out.Int(int(in.Parent))
	}
	{
		const prefix string = ",\"author\":"
		out.RawString(prefix)
		out.String(string(in.Author))
	}
	{
		const prefix string = ",\"message\":"
		out.RawString(prefix)
		out.String(string(in.Message))
	}
	{
		const prefix string = ",\"isEdited\":"
		out.RawString(prefix)
		out.Bool(bool(in.IsEdited))
	}
	{
		const prefix string = ",\"forum\":"
		out.RawString(prefix)
		out.String(string(in.Forum))
	}
	{
		const prefix string = ",\"thread\":"
		out.RawString(prefix)
		out.Int(int(in.Thread))
	}
	{
		const prefix string = ",\"created\":"
		out.RawString(prefix)
		out.String(string(in.Created))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v PostDTO) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonFbeb1674EncodeGithubComMmikhail2001TechnoparkDbProjectInternalAppDeliveryThreadDto1(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v PostDTO) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonFbeb1674EncodeGithubComMmikhail2001TechnoparkDbProjectInternalAppDeliveryThreadDto1(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *PostDTO) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonFbeb1674DecodeGithubComMmikhail2001TechnoparkDbProjectInternalAppDeliveryThreadDto1(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *PostDTO) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonFbeb1674DecodeGithubComMmikhail2001TechnoparkDbProjectInternalAppDeliveryThreadDto1(l, v)
}
