server:
  bind_id: 0.0.0.0
  port: 5000
  read_timeout: 10 # seconds
  write_timeout: 10
  read_header_timeout: 5
  shutdown_timeout: 5
postgres:
  # password from env
  user: postgres
  dbname: postgres
  password: postgres
  host: 0.0.0.0
  port: 5432
  sslmode: disable
  max_open_cons: 100

